### ISSUE TITLE
KeyError: 'g'

### ISSUE THREAD

**Issue by palomo11** [zoubohao/Deepurify#1]
Hi, I'm trying to run Deepurify but I'm getting an error.

This is the code i'm running

```
export DeepurifyInfoFiles=/data/software/deepurify/DeepurifyInfoFiles

deepurify clean -i /data/dereplicate_genomes_099_S1_S2_S3_S4_all_bins/dereplicated_genomes/ -o /data/drep_099_S1_S2_S3_S4_all_bins_deepurify/ --bin_suffix fa --gpu_num 0
```

This is the error I'm getting

```
Traceback (most recent call last):
  File "/data/software/python/anaconda3/2021.11/envs/deepurify_v124/lib/python3.9/site-packages/Deepurify/LabelContigTools/LabelBinUtils.py", line 831, in labelBinsFolder
    labelONEBinAndWrite(
  File "/data/software/python/anaconda3/2021.11/envs/deepurify_v124/lib/python3.9/site-packages/Deepurify/LabelContigTools/LabelBinUtils.py", line 729, in labelONEBinAndWrite
    name2annotated, name2maxList = labelBinFastaFile(
  File "/data/software/python/anaconda3/2021.11/envs/deepurify_v124/lib/python3.9/site-packages/Deepurify/LabelContigTools/LabelBinUtils.py", line 627, in labelBinFastaFile
    ori_rev_tensor, feature_3Mer, feature_3Mer_rev_com, feature_4Mer, feature_4Mer_rev_com = ConvertSeqToImageTensorMoreFeatures(
  File "/data/software/python/anaconda3/2021.11/envs/deepurify_v124/lib/python3.9/site-packages/Deepurify/SeqProcessTools/SequenceUtils.py", line 195, in ConvertSeqToImageTensorMoreFeatures
    oriSeqIndex = torch.from_numpy(np.array(list(map(lambda x: nt2index[x], oriSeq)), dtype=np.int64)).view([max_model_len, 1])
  File "/data/software/python/anaconda3/2021.11/envs/deepurify_v124/lib/python3.9/site-packages/Deepurify/SeqProcessTools/SequenceUtils.py", line 195, in <lambda>
    oriSeqIndex = torch.from_numpy(np.array(list(map(lambda x: nt2index[x], oriSeq)), dtype=np.int64)).view([max_model_len, 1])
KeyError: 'g'
```

**Comment by zoubohao** [comment]
Hi, 

Thanks for using Deepurify.

I think that this error comes from the fasta files. Please check your fatsa files to ensure that all DNA sequences utilize uppercase letters (A,T,C,G) instead of lowercase letters (a,t,c,g).
